export interface ApiCommandContract {
  functionName: string;
  commandName: string;
  argKeys: string[];
}

export const API_COMMAND_CONTRACTS = [
  { functionName: "listNotes", commandName: "list_notes", argKeys: [] },
  { functionName: "readNote", commandName: "read_note", argKeys: ["relativePath"] },
  { functionName: "searchNotes", commandName: "search_notes", argKeys: ["query"] },
  { functionName: "writeNote", commandName: "write_note", argKeys: ["relativePath", "content"] },
  { functionName: "getNotesRootPath", commandName: "get_notes_root_path", argKeys: [] },
  { functionName: "classifyMarkdownSavePath", commandName: "classify_markdown_save_path", argKeys: ["absolutePath"] },
  { functionName: "writeExternalMarkdownFile", commandName: "write_external_markdown_file", argKeys: ["absolutePath", "content"] },
  { functionName: "saveNoteAsset", commandName: "save_note_asset", argKeys: ["noteRelativePath", "bytes", "mimeType"] },
  { functionName: "resolveNoteAssetUrl", commandName: "resolve_note_asset_url", argKeys: ["noteRelativePath", "imageSrc"] },
  { functionName: "importLuoguInsight", commandName: "import_luogu_insight", argKeys: ["problemId", "problemTitle", "submissionId", "sourceCode"] },
  { functionName: "getLuoguConfig", commandName: "get_luogu_config", argKeys: [] },
  { functionName: "saveLuoguConfig", commandName: "save_luogu_config", argKeys: ["config"] },
  { functionName: "updateLuoguLastSubmissionId", commandName: "update_luogu_last_submission_id", argKeys: ["lastSubmissionId"] },
  { functionName: "testLuoguConnection", commandName: "test_luogu_connection", argKeys: [] },
  { functionName: "readLuoguProblemContent", commandName: "read_luogu_problem_content", argKeys: ["input"] },
  { functionName: "previewLuoguSubmissions", commandName: "preview_luogu_submissions", argKeys: ["limit"] },
  { functionName: "previewLuoguSubmissionPage", commandName: "preview_luogu_submission_page", argKeys: ["page"] },
  { functionName: "importLuoguSubmission", commandName: "import_luogu_submission", argKeys: ["submissionId", "autoCommit"] },
  { functionName: "prepareLuoguSubmissionNote", commandName: "prepare_luogu_submission_note", argKeys: ["submissionId", "rules"] },
  { functionName: "writeLuoguPreparedNote", commandName: "write_luogu_prepared_note", argKeys: ["relativePath", "markdown", "autoCommit", "writeMode"] },
  { functionName: "syncLuoguInsights", commandName: "sync_luogu_insights", argKeys: [] },
  { functionName: "getKnowledgeGraph", commandName: "get_knowledge_graph", argKeys: [] },
  { functionName: "rebuildKnowledgeGraph", commandName: "rebuild_knowledge_graph", argKeys: [] },
  { functionName: "getKnowledgeAssets", commandName: "get_knowledge_assets", argKeys: [] },
  { functionName: "getKnowledgeLocalGraph", commandName: "get_knowledge_local_graph", argKeys: ["nodeId", "hops", "limit"] },
  { functionName: "getKnowledgeRelationshipSuggestions", commandName: "get_knowledge_relationship_suggestions", argKeys: [] },
  { functionName: "getKnowledgeReviewSlices", commandName: "get_knowledge_review_slices", argKeys: [] },
  { functionName: "writeKnowledgeAsset", commandName: "write_knowledge_asset", argKeys: ["relativePath", "markdown", "overwrite"] },
  { functionName: "getTagTaxonomyConfig", commandName: "get_tag_taxonomy_config", argKeys: [] },
  { functionName: "saveTagTaxonomyConfig", commandName: "save_tag_taxonomy_config", argKeys: ["config"] },
  { functionName: "getBlogConfig", commandName: "get_blog_config", argKeys: [] },
  { functionName: "saveBlogConfig", commandName: "save_blog_config", argKeys: ["config"] },
  { functionName: "resetTagTaxonomyConfig", commandName: "reset_tag_taxonomy_config", argKeys: [] },
  { functionName: "getAiConfig", commandName: "get_ai_config", argKeys: [] },
  { functionName: "saveAiConfig", commandName: "save_ai_config", argKeys: ["config"] },
  { functionName: "testAiConnection", commandName: "test_ai_connection", argKeys: [] },
  { functionName: "saveAiProvider", commandName: "save_ai_provider", argKeys: ["provider"] },
  { functionName: "deleteAiProvider", commandName: "delete_ai_provider", argKeys: ["providerId"] },
  { functionName: "setDefaultAiModel", commandName: "set_default_ai_model", argKeys: ["providerId", "modelId"] },
  { functionName: "syncAiProviderModels", commandName: "sync_ai_provider_models", argKeys: ["providerId"] },
  { functionName: "syncAiProviderModelsDraft", commandName: "sync_ai_provider_models_draft", argKeys: ["provider"] },
  { functionName: "testAiProvider", commandName: "test_ai_provider", argKeys: ["providerId"] },
  { functionName: "testAiProviderDraft", commandName: "test_ai_provider_draft", argKeys: ["provider"] },
  { functionName: "addAiProviderModel", commandName: "add_ai_provider_model", argKeys: ["providerId", "modelId"] },
  { functionName: "deleteAiProviderModel", commandName: "delete_ai_provider_model", argKeys: ["providerId", "modelId"] },
  { functionName: "searchWebSources", commandName: "search_web_sources", argKeys: ["request"] },
  { functionName: "planSearchQueries", commandName: "plan_search_queries", argKeys: ["input"] },
  { functionName: "fetchWebSourceExcerpts", commandName: "fetch_web_source_excerpts", argKeys: ["input"] },
  { functionName: "searchLocalNotes", commandName: "search_local_notes", argKeys: ["input"] },
  { functionName: "clearWebCache", commandName: "clear_web_cache", argKeys: [] },
  { functionName: "testWebSearchConnection", commandName: "test_web_search_connection", argKeys: ["input"] },
  { functionName: "getWebCacheStatus", commandName: "get_web_cache_status", argKeys: [] },
  { functionName: "getLocalNoteIndexStatus", commandName: "get_local_note_index_status", argKeys: [] },
  { functionName: "rebuildLocalNoteIndex", commandName: "rebuild_local_note_index", argKeys: [] },
  { functionName: "getPromptCitationContractStatus", commandName: "get_prompt_citation_contract_status", argKeys: [] },
  { functionName: "runNotexSearchSelfCheck", commandName: "run_notex_search_self_check", argKeys: [] },
  { functionName: "generateNoteMetadata", commandName: "generate_note_metadata", argKeys: ["relativePath", "markdownContent", "tagTaxonomyContext"] },
  { functionName: "polishNoteBody", commandName: "polish_note_body", argKeys: ["relativePath", "markdownContent"] },
  { functionName: "chatWithCurrentNote", commandName: "chat_with_current_note", argKeys: ["question", "context", "providerId", "modelId"] },
  { functionName: "suggestNoteTags", commandName: "suggest_note_tags", argKeys: ["context", "providerId", "modelId"] },
  { functionName: "polishSelectedText", commandName: "polish_selected_text", argKeys: ["context", "providerId", "modelId"] },
  { functionName: "polishFullNote", commandName: "polish_full_note", argKeys: ["context", "instruction", "providerId", "modelId"] },
  { functionName: "startCurrentNoteChatStream", commandName: "chat_with_current_note_stream", argKeys: ["input"] },
  { functionName: "listAiPrompts", commandName: "list_ai_prompts", argKeys: [] },
  { functionName: "readAiPrompt", commandName: "read_ai_prompt", argKeys: ["fileName"] },
  { functionName: "saveAiPrompt", commandName: "save_ai_prompt", argKeys: ["fileName", "content"] },
  { functionName: "resetAiPromptToDefault", commandName: "reset_ai_prompt_to_default", argKeys: ["fileName"] },
  { functionName: "polishAiPromptTemplate", commandName: "polish_ai_prompt_template", argKeys: ["fileName", "content"] },
  { functionName: "deleteNote", commandName: "delete_note", argKeys: ["relativePath"] },
  { functionName: "renameNote", commandName: "rename_note", argKeys: ["oldRelativePath", "newRelativePath"] },
  { functionName: "createNoteFolder", commandName: "create_note_folder", argKeys: ["relativePath"] },
  { functionName: "renameNoteFolder", commandName: "rename_note_folder", argKeys: ["oldRelativePath", "newRelativePath"] },
  { functionName: "deleteNoteFolder", commandName: "delete_note_folder", argKeys: ["relativePath"] },
  { functionName: "openBlog", commandName: "open_blog", argKeys: [] },
  { functionName: "restartBlogServer", commandName: "restart_blog_server", argKeys: [] },
  { functionName: "openNotesFolder", commandName: "open_notes_folder", argKeys: [] },
  { functionName: "hideMainWindow", commandName: "hide_main_window", argKeys: [] },
] as const satisfies readonly ApiCommandContract[];
